language: cpp

sudo: false

compiler:
  - clang
  - gcc

#addons:
#  apt:
#    sources:
#    - ubuntu-sdk-team

addons:
  apt:
    packages:
    - cppcheck
    - qt5-qmake
    - qtbase5-dev
    - libqt5xmlpatterns5-dev

before_script:
  - cppcheck --error-exitcode=1 --quiet .
  - qmake -qt=qt5
  - pushd test
  - qmake -qt=qt5
  - popd

script:
  - make all
  - pushd test
  - make all && make check
  - popd

after_failure:
  - pushd test/protobuf/testdata/
  - diff -u golden_message.expected.json golden_message.result.json
  - diff -u golden_packed_fields_message.expected.json golden_packed_fields_message.result.json
  - diff -u google_message1.dat.expected.json google_message1.dat.result.json
  - diff -u google_message2.dat.expected.json google_message2.dat.result.json
  - popd
